### ISSUE TITLE
Notifications do not update their position when switching to an external display and the resolution changes

### ISSUE THREAD

**Issue by Mystechry** [project-sbc/Handheld-Control-Panel#16]
- When I change resolution via closing the lid and attaching to external display
-> The side panel resizes properly
-> Notifications do not update their position values
-> Notifications now appear somewhere in the middle of the screen. Probably taking the old resolution values to calculate the coordinates

**Comment by project-sbc** [comment]
Fixed in upcoming release, I needed to create a new notification manager everytime I send a notification
