### ISSUE TITLE
Error: ChangeTDP.cs: Parse intel tdp from result: Additional non-parsable characters are at the end of the string.

### ISSUE THREAD

**Issue by cassimirov** [project-sbc/Handheld-Control-Panel#32]
![20230822_115218](https://github.com/project-sbc/Handheld-Control-Panel/assets/142914748/4f98982d-74de-4d2c-b585-02593436885f)

Hi.

Just downloaded the files today to test on my GPD Win 3 (1195g7), and now I am facing this issue (from the image). Already changed the value on regedit, but that didn't solve the error for me.

Is there any workaround for this?

**Comment by project-sbc** [comment]
Yeah make sure core isolation is off then Restart the device

Best Regards,
Chris

WeChat: ProjectSBC
QQ: 1619238952
________________________________
From: cassimirov ***@***.***>
Sent: Tuesday, August 22, 2023 10:57:57 AM
To: project-sbc/Handheld-Control-Panel ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [project-sbc/Handheld-Control-Panel] Error: ChangeTDP.cs: Parse intel tdp from result: Additional non-parsable characters are at the end of the string. (Issue #32)


[20230822_115218]<https://user-images.githubusercontent.com/142914748/262392585-4f98982d-74de-4d2c-b585-02593436885f.jpg>

Hi.

Just downloaded the files today to test on my GPD Win 3 (1195g7), and now I am facing this issue (from the image). Already changed the value on regedit, but that didn't solve the error for me.

Is there any workaround for this?

**Comment by cassimirov** [comment]
Tried here, unfortunately that didn't work.

**Comment by cassimirov** [comment]
Sorry, that worked great! Thank you so much!!!

**Comment by cassimirov** [comment]
Everything ok now!!
